name: CI/CD Pipeline

on:
  push:
    branches: ['**']

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Run tests
        run: mvn test

  build-and-push:
    name: Build & Publish Docker Image
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          
      - name: Build package without tests
        run: mvn clean package -DskipTests
        
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" \
             | docker login ghcr.io \ 
               -u "${{ github.actor }}" --password-stdin
               
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }} \
            .                                                # собираем образ :contentReference[oaicite:6]{index=6}
            
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}  # пушим в GHCR :contentReference[oaicite:7]{index=7}
